version: '3.8'
services:
    backend:
        image: backend
        build: ./backend
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./backend:/backend
        ports:
            - '8000:8000'
    
    frontend:
        image: site-frontend
        build: ./site-frontend
        volumes:
            - front_build:/site-frontend/build
        ports:
            - '3000:3000'
        
        environment:
            - NODE_ENV=production
    
    proxy:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - front_build:/var/www/front_build
        ports:
            - '80:8080'
        depends_on:
            - backend
            - frontend

volumes:
    front_build:
    # external: True